session:
  secret: "white-rabbit"
ldap:
  # Make production.yml and set NODE_ENV=production when run as production
  url: "ldap://localhost:389"
  bindDN: "cn=admin,dc=example,dc=com"
  bindCredentials: "********"
  searchBase: "dc=example,dc=com"
  searchFilter: "(uid={{username}})"
mongodb:
  url: "mongodb://user:********@localhost:27017/slacklog?autoReconnect=true"
  db: "slacklog"
  collection: "aosn"
search:
  limit: 30
